import { prisma } from "./db";
import { buildSha } from "./build-info";
import { installShape, isContainerised } from "./install-shape";
import { storageReport } from "./storage-usage";
import { schedulerStarted, schedulerLastTickAgoMs } from "./scheduler";
import { getIntegrationStatus } from "./integrations";
import { getIdentity } from "./identity";

/**
 * The support bundle (#395).
 *
 * An operator without shell access has no way to answer "what version, what
 * install shape, is the scheduler running, is the disk full" — which is most of
 * what any support conversation starts with. This assembles it.
 *
 * THE DESIGN RULE, and it is the whole reason this is safe to ship: NO SECRET
 * VALUE IS EVER READ. Not from `process.env`, not from the database. Every
 * source here is one that already returns a redacted or public shape, and the
 * environment is reported as NAMES ONLY with a present/absent flag.
 *
 * That is deliberately stricter than "redact the output". A redactor has to know
 * every secret in order to remove it, and since #59 the DATABASE is the primary
 * store for every integration credential while the environment is only a
 * fallback — so a redactor built around `process.env` is a no-op on exactly the
 * instances configured through the admin panel, which is the documented path. It
 * would look green in a test that plants environment sentinels while the real
 * password walked straight through. Not reading secrets at all has no such
 * failure mode.
 *
 * DELIBERATELY OMITTED: a tail of recent log lines. It is the most useful thing
 * a support bundle could carry and the only part that can contain arbitrary
 * strings — an @atproto error, a stack trace, a cache key. Making that safe
 * needs redaction against RESOLVED credentials (decrypted from the database, not
 * read from the environment), which is a separate piece of work with its own
 * failure mode. Tracked separately rather than bolted on here.
 */

/** Environment variables FediHome reads. NAMES ONLY — values are never touched. */
const ENV_NAMES = [
  "DATABASE_URL",
  "SITE_URL",
  "FEDI_HANDLE",
  "FEDI_DOMAIN",
  "ADMIN_SECRET",
  "ADMIN_PASSWORD",
  "NODE_ENV",
  "PORT",
  "FEDIHOME_UPLOADS_DIR",
  "FEDIHOME_FEDI_CACHE_MB",
  "FEDIHOME_UPDATE_URL",
  "FEDIHOME_UPDATE_TEXT",
  "BLUESKY_HANDLE",
  "BLUESKY_APP_PASSWORD",
  "BLUESKY_SERVICE",
  "THREADS_USER_ID",
  "THREADS_ACCESS_TOKEN",
  "TRUST_PROXY",
  "APP_TOKEN_TTL_DAYS",
  "ADMIN_SESSION_TTL_DAYS",
] as const;

const line = (k: string, v: unknown) => `${k.padEnd(26)} ${v === null || v === undefined ? "—" : String(v)}`;

export async function collectDiagnostics(): Promise<string> {
  const out: string[] = [];
  const section = (t: string) => out.push("", `## ${t}`, "");

  out.push("FediHome support bundle");
  out.push("Generated by the owner from Admin. Contains no passwords, tokens or keys.");

  section("Version and install");
  let version = "unknown";
  try {
    const pkg = await import("../../package.json");
    version = (pkg as { version?: string }).version ?? (pkg as { default?: { version?: string } }).default?.version ?? "unknown";
  } catch {
    /* reported as unknown */
  }
  out.push(line("version", version));
  out.push(line("build sha", buildSha()));
  out.push(line("install shape", installShape()));
  out.push(line("containerised", isContainerised()));
  out.push(line("node", process.version));
  out.push(line("platform", `${process.platform} ${process.arch}`));
  out.push(line("uptime (s)", Math.round(process.uptime())));

  section("Identity");
  // All three are published in every post — public by construction.
  const id = getIdentity();
  out.push(line("site url", id.siteUrl));
  out.push(line("handle", id.fediHandle));
  out.push(line("domain", id.fediDomain));
  out.push(line("actor id", id.actorId));

  section("Database");
  try {
    await prisma.$queryRaw`SELECT 1`;
    out.push(line("reachable", "yes"));
  } catch (e) {
    // The message only, never the connection string — a Prisma error can carry
    // the URL, and that URL carries the password.
    out.push(line("reachable", `NO (${e instanceof Error ? e.name : "error"})`));
  }
  try {
    const [posts, fediPosts, followers, following, failedDeliveries, failedCrossposts, maintenance] =
      await Promise.all([
        prisma.post.count(),
        prisma.fediPost.count(),
        prisma.fediFollower.count(),
        prisma.fediFollowing.count(),
        prisma.failedDelivery.count(),
        prisma.failedCrosspost.count(),
        prisma.maintenanceItem.count({ where: { resolvedAt: null } }),
      ]);
    for (const [k, v] of [
      ["posts", posts], ["fediverse posts", fediPosts], ["followers", followers],
      ["following", following], ["failed deliveries", failedDeliveries],
      ["failed crossposts", failedCrossposts], ["open maintenance items", maintenance],
    ] as const) out.push(line(k, v));
  } catch {
    out.push(line("counts", "unavailable"));
  }

  section("Scheduler");
  out.push(line("started", schedulerStarted()));
  const ago = schedulerLastTickAgoMs();
  out.push(line("last tick", ago === null ? "never" : `${Math.round(ago / 1000)}s ago`));

  section("Storage");
  try {
    const s = await storageReport();
    out.push(line("uploads dir", s.uploadsDir));
    out.push(line("status", s.status));
    out.push(line("available bytes", s.availableBytes));
    out.push(line("volume bytes", s.volumeBytes));
  } catch {
    out.push(line("storage", "unavailable"));
  }

  section("Integrations");
  try {
    // Already secret-free by construction — a test pins that it never returns a
    // password, so this reuses that guarantee rather than making a second one.
    const s = await getIntegrationStatus();
    out.push(line("bluesky", s.bluesky.configured ? `configured (${s.bluesky.source})` : "not configured"));
    out.push(line("threads", s.threads.configured ? `configured (${s.threads.source})` : "not configured"));
    out.push(line("email", s.dayOne.configured ? `configured (${s.dayOne.source})` : "not configured"));
  } catch {
    out.push(line("integrations", "unavailable"));
  }

  section("Environment (names only — no values)");
  for (const name of ENV_NAMES) {
    out.push(line(name, process.env[name] === undefined ? "not set" : "set"));
  }

  out.push("");
  return out.join("\n");
}
