-- Outbound follow state (#348). Additive + idempotent.
--
-- Apply with: npx prisma db execute --file prisma/manual-migrations/2026-07-28-fedifollowing-accepted.sql
-- Or (preferred): npx prisma db push
--
-- NOTE THE ABSENCE OF A BACKFILL UPDATE, deliberately. These files re-run, so an
-- `UPDATE ... WHERE "accepted" IS NULL`-style backfill would re-fire and silently
-- promote genuinely-pending follows to accepted. DEFAULT true already backfills
-- every existing row at ADD COLUMN time, once, and IF NOT EXISTS makes the whole
-- file a no-op from the second run onward. See README.md in this directory.
ALTER TABLE "FediFollowing" ADD COLUMN IF NOT EXISTS "accepted" BOOLEAN NOT NULL DEFAULT true;
